### ISSUE TITLE
Slider Breaks After Page Reload in Firefox on Mac

### ISSUE THREAD

**Issue by roughsedge** [WallopSlider/wallopslider.github.io#1]
I've noticed an issue with Firefox on Mac OS whereby the slider breaks after you refresh the page. If you run through the slider to the last image and then refresh the page, the slider no longer works. it just shows the first image and the previous button only, but the button doesn't work. Doing a hard refresh resets the slider and it works again but will break again after another refresh.
The issue isn't specific to my setup as the issue is present in all of the demo pages. 
is there a fix for this?
i'm using Firefox 34.0. i've also tested it in Chrome and Safari on Mac and the issue isn't there.

**Comment by peduarte** [comment]
That. Is. Weird.

I am in the process of releasing v2.
Will do some tests then and update this.

**Comment by roughsedge** [comment]
i've found that setting carousel to true stops it from breaking entirely, but it's not a perfect fix. it seems to be an issue with the navigation as it gets stuck on the least slide but only shows the next button, hence the carousel kind of fixing it.
cheers.

**Comment by peduarte** [comment]
:+1:

**Comment by peduarte** [comment]
Released V2 with loads of fixes :)
